version: "3"
services:
  nginx-proxy:
    image: jc21/nginx-proxy-manager:2.0.14
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    networks:
      - proxy
    volumes:
      - ./config.json:/app/config/production.json
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db
    environment:
    # if you want pretty colors in your docker logs:
    - FORCE_COLOR=1
  nginx-db:
    image: mariadb:10.3
    container_name: nginx-db
    restart: always
    ports:
      - 3306:3306    
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - proxy
    volumes:
      - ./data/mysql:/var/lib/mysql
#  portainer:
#    image: portainer/portainer
#    container_name: portainer
#    command: -H unix:///var/run/docker.sock
#    restart: always
#    environment:
#      - VIRTUAL_HOST=${VIRTUAL_HOST}
#    networks:
#      - proxy
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - portainer_data:/data

networks:
  proxy:

#volumes:
#  portainer_data:

